// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"wire-use/app"
)

// Injectors from wiring.go:

func InitializeServices() (*app.UserService, error) {
	database := app.NewDatabase()
	userService := app.NewUserService(database)
	return userService, nil
}
